apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lws.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/part-of: lws
  {{- include "lws.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}